### ISSUE TITLE
Dependency versions/revisions? Cargo.lock?

### ISSUE THREAD

**Issue by dtzWill** [vhdirk/inox#2]
Hi!

I was interested in checking out this project, but am having trouble building due to what seems to primarily be unclear dependencies.  The Cargo.toml files seem to be intended for use with local copies of the dependencies (notmuch-rs, etc.); is this correct?
I see you have clones of many of the dependencies--but am running into problems building using latest upstream git or your mirrors... I can share details of the problems if that's unexpected, but so far the problems appear to be X uses type that was removed months ago in Y, etc.-- that is, I think it'd be best to get an idea what's expected/known to work first :).

Towards this, a Cargo.lock file would be useful, at least for me, if that's something you'd be willing to construct and include.

I'm new to Rust and its ecosystem, so I apologize if this doesn't quite make sense.  Thanks for sharing this project regardless! :)

**Comment by vhdirk** [comment]
This project is still _very_ much in its infancy and currently isn't useful in any way. The biggest hurdle at this point is the subclassing infrastructure in gtk-rs. It's recently been merged into glib-rs, but it's not complete yet.
So, while developing this project, I spend my time fixing issues in:
* notmuch-rs
* gmime-rs
* gtk-rs (an all of their subprojects)

Once most blocking issues there are resolved, I can remove my forks and local copies and get this project useful to others.

**Comment by vhdirk** [comment]
Closing as it's not using any local versions any more
